export const SEARCH_FORM_ITEMS_LIMIT = 5;

export const SEARCH_RESULTS = {
  REQUEST: 'SEARCH_RESULTS_REQUEST',
  SUCCESS: 'SEARCH_RESULTS_SUCCESS',
  FAILURE: 'SEARCH_RESULTS_FAILURE',
};
export const GET = {
  ACTIVE_ITEM: 'GET_ACTIVE_ITEM',
};
export const SET = {
  SEARCH: {
    FIELD: 'SET_SEARCH_FIELD',
    ACTIVE_ITEM: 'SET_ACTIVE_ITEM',
    ACTIVE_ITEM_INCREMENT: 'SET_ACTIVE_ITEM_INCREMENT',
    ACTIVE_ITEM_DECREMENT: 'SET_ACTIVE_ITEM_DECREMENT',
  },
};
