export const FETCH = {
  ENTITY: {
    START: 'FETCH_ENTITY_START',
    SUCCESS: 'FETCH_ENTITY_SUCCESS',
    ERROR: 'FETCH_ENTITY_ERROR',
  },
  CATEGORIES: {
    START: 'FETCH_CATEGORIES_START',
    SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    ERROR: 'FETCH_CATEGORIES_ERROR',
  },
  PRODUCTS: {
    START: 'FETCH_PRODUCTS_START',
    SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    ERROR: 'FETCH_PRODUCTS_ERROR',
  },
};
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const CHANGE_VIEW_STATUS = 'CHANGE_VIEW_STATUS';
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS';
