export const FETCH = {
  ENTITY: {
    START: 'FETCH_ENTITY_START',
    SUCCESS: 'FETCH_ENTITY_SUCCESS',
    ERROR: 'FETCH_ENTITY_ERROR',
  },
  CATEGORIES: {
    START: 'FETCH_CATEGORIES_START',
    SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    ERROR: 'FETCH_CATEGORIES_ERROR',
  },
  PRODUCTS: {
    START: 'FETCH_PRODUCTS_START',
    SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
    ERROR: 'FETCH_PRODUCTS_ERROR',
  },
  REGISTER: {
    START: 'FETCH_REGISTER_START',
    SUCCESS: 'FETCH_REGISTER_SUCCESS',
    ERROR: 'FETCH_REGISTER_ERROR',
  },
  LOGIN: {
    START: 'FETCH_LOGIN_START',
    SUCCESS: 'FETCH_LOGIN_SUCCESS',
    ERROR: 'FETCH_LOGIN_ERROR',
  },
  AUTH_USER: {
    START: 'FETCH_AUTH_USER_START',
    SUCCESS: 'FETCH_AUTH_USER_SUCCESS',
    ERROR: 'FETCH_AUTH_USER_ERROR',
  },
  ORDERS: {
    START: 'FETCH_ORDERS_START',
    SUCCESS: 'FETCH_ORDERS_SUCCESS',
    ERROR: 'FETCH_ORDERS_ERROR',
  },
  SEARCH: {
    START: 'FETCH_SEARCH_START',
    SUCCESS: 'FETCH_SEARCH_SUCCESS',
    ERROR: 'FETCH_SEARCH_ERROR',
  },
  PRODUCT_BY_ID: {
    START: 'FETCH_PRODUCT_BY_ID_START',
    SUCCESS: 'FETCH_PRODUCT_BY_ID_SUCCESS',
    ERROR: 'FETCH_PRODUCT_BY_ID_ERROR',
  },
};

export const SIGN_UP = {
  FIELD: {
    EMAIL: 'SIGN_UP_FIELD_EMAIL',
    PASSWORD: 'SIGN_UP_FIELD_PASSWORD',
  },
  NO_VALID: {
    EMAIL: 'SIGN_UP_NO_VALID_EMAIL',
    PASSWORD: 'SIGN_UP_NO_VALID_PASSWORD',
  },
};
export const SIGN_IN = {
  FIELD: {
    EMAIL: 'SIGN_IN_FIELD_EMAIL',
    PASSWORD: 'SIGN_IN_FIELD_PASSWORD',
    REMEMBER_ME: 'SIGN_IN_FIELD_REMEMBER_ME',
  },
  NO_VALID: {
    EMAIL: 'SIGN_IN_NO_VALID_EMAIL',
    PASSWORD: 'SIGN_IN_NO_VALID_PASSWORD',
  },
};
export const SEARCH = {
  FIELD: 'SEARCH_FIELD',
  ACTIVE_ITEM: {
    CHANGE: 'SEARCH_ACTIVE_ITEM_CHANGE',
    INCREMENT: 'SEARCH_ACTIVE_ITEM_INCREMENT',
    DECREMENT: 'SEARCH_ACTIVE_ITEM_DECREMENT',
  },
};
export const CHANGE_AUTH_TOKEN = 'CHANGE_AUTH_TOKEN';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const TOGGLE_TOOLTIP = 'TOGGLE_TOOLTIP';
export const CHANGE_VIEW_STATUS = 'CHANGE_VIEW_STATUS';
export const CHANGE_FILTERS = 'CHANGE_FILTERS';
