export const DIGITAL_REG = /^[0-9]*$/;

export const FILTER_CATEGORIES = {
  REQUEST: 'FILTER_CATEGORIES_REQUEST',
  SUCCESS: 'FILTER_CATEGORIES_SUCCESS',
  FAILURE: 'FILTER_CATEGORIES_FAILURE',
};
export const SET = {
  FILTERS: 'SET_FILTERS',
  ORDERS: 'SET_ORDERS',
};
